packet_id: 0x45
name: RequestNetworkSettings
description: "Client sends a command string to be executed."

fields:
  - name: clientNetworkVersion
    type:
      family: primitive
      name: int32
      encoding: big-endian
